stages:
  - Puppet 5
  - Puppet 6
  - push2github

xenial:puppet5:
  image: scalecommerce/xenial:1.11
  stage: Puppet 5
  script:
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_postgresql.rb
    - mv ./test/hieradata/override.yaml.disabled  ./test/hieradata/override.yaml
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_postgresql_override.rb
    - mv ./test/hieradata/override.yaml  ./test/hieradata/override.yaml.disabled

xenial:puppet6:
  image: scalecommerce/xenial:1.11
  stage: Puppet 6
  script:
    - ./test/install-puppet6.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_postgresql.rb
    - mv ./test/hieradata/override.yaml.disabled  ./test/hieradata/override.yaml
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_postgresql_override.rb
    - mv ./test/hieradata/override.yaml  ./test/hieradata/override.yaml.disabled

push2github:
  image: scalecommerce/xenial:1.11
  stage: push2github
  script:
    - git push --quiet --mirror https://$GITHUB_TOKEN@github.com/ScaleCommerce/puppet-sc_postgresql.git
