stages:
  - test
  - push2github

focal:puppet7:
  stage: test
  image: scalecommerce/focal-supervisord:1.5
  tags:
    - dind
  script:
    - ./test/install-puppet7.sh
    - ./test/install.sh
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_postgresql.rb
    - mv ./test/hieradata/override.yaml.disabled  ./test/hieradata/override.yaml
    - puppet apply -v ./test/site.pp
    - inspec exec ./test/inspec/sc_postgresql_override.rb
    - mv ./test/hieradata/override.yaml  ./test/hieradata/override.yaml.disabled

push2github:
  stage: push2github
  image: scalecommerce/focal-supervisord:1.5
  tags:
    - dind
  script:
    - git clone --mirror $CI_REPOSITORY_URL .git-mirror
    - cd .git-mirror
    - git remote set-url --push origin  https://$GITHUB_TOKEN@github.com/ScaleCommerce/$CI_PROJECT_NAME.git
    - git push --quiet --mirror